#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p mate-hud 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p mate-hud  || true
fi

if command -v py3compile >/dev/null 2>&1; then
	py3compile -p mate-hud /usr/lib/mate-hud
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p mate-hud /usr/lib/mate-hud || true
fi

# End automatically added section
